recipes/urls.py
from django.urls import path
from .views import RecipeListView, RecipeDetailView, HomeView, search

app_name = "recipes"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),  # Add this line for the homepage
    path("list/", RecipeListView.as_view(), name="list"),
    path("list/<pk>", RecipeDetailView.as_view(), name="detail"),
    path("search/", search, name="search"),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

recipes/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

difficulty = (
    ("easy", "Easy"),
    ("intermediate", "Intermediate"),
    ("hard", "Hard"),
)


class Recipe(models.Model):
    name = models.CharField(max_length=225)
    ingredients = models.CharField(max_length=225)
    cooking_time = models.IntegerField(default=10)
    difficulty = models.CharField(max_length=30, choices=difficulty)
    pic = models.ImageField(upload_to="recipes", default="no_image.png")

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={"pk": self.pk})

    def get_main_html(self):
        return reverse("recipes:main", kwargs={"pk": self.pk})

recipes/forms.py
from django import forms  # type: ignore # import django forms

CHART__CHOICES = (  # specify choices as a tuple
    ("#1", "Bar chart"),  # when user selects "Bar chart", it is stored as "#1"
    ("#2", "Pie chart"),
    ("#3", "Line chart"),
)


# define class-based Form imported from Django forms
class RecipeSearchForm(forms.Form):
    recipe_title = forms.CharField(max_length=120)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

recipes/views.py
from django.shortcuts import render  # imported by default
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
)  # to display lists and details
from .models import Recipe  # to access Book model

from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import RecipeSearchForm
from .models import Recipe
from .utils import get_recipe_name_from_id
import pandas as pd


# Create your views here.
class RecipeListView(LoginRequiredMixin, ListView):  # class-based view
    model = Recipe  # specify model
    template_name = "recipes/main.html"  # specify template


class RecipeDetailView(LoginRequiredMixin, DetailView):  # class-based view
    model = Recipe  # specify model
    template_name = "recipes/detail.html"  # specify template


class HomeView(TemplateView):  # Add this class for the homepage
    template_name = "recipes/home.html"


def search(request):
    form = RecipeSearchForm(request.POST or None)
    recipes_df = None
    if request.method == "POST":
        recipe_title = request.POST.get("recipe_title")
        chart_type = request.POST.get("chart_type")
        # display in terminal - needed for debugging during development only
        qs = Recipe.objects.filter(name__icontains=recipe_title)
        if qs:
            recipes_df = pd.DataFrame(qs.values())
            recipes_df["name"] = recipes_df["id"].apply(
                get_recipe_name_from_id
            )
            recipes_df["pic"] = recipes_df["pic"].apply(
                lambda x: f'<img src="{x}" width="100" height="100"/>'
            )

            recipes_df = recipes_df.to_html(escape=False)

    context = {
        "form": form,
        "recipes_df": recipes_df,
    }

    return render(request, "recipes/search.html", context)

src/views.py
# Django authentication libaries
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

# Django Form for authentication
from django.contrib.auth.forms import AuthenticationForm


def login_view(request):
    error_message = None
    form = AuthenticationForm()
    # When user hits 'login' button, then POST request is sent is generated
    if request.method == "POST":
        # read the data sent by the form via POST request
        form = AuthenticationForm(data=request.POST)
        # check if the form is valid
        if form.is_valid():
            # get the username and password
            username = form.cleaned_data["username"]  # Read username
            password = form.cleaned_data["password"]  # Read password

            # use Django's built-in authenticate function to check if the user is valid
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("recipes:list")  # send user to the desired page
        else:
            error_message = "Oops! Something went wrong."  # error message
    context = {"form": form, "error_message": error_message}
    return render(request, "auth/login.html", context)


def logout_view(request):
    logout(request)  # use Django's built-in logout function
    return redirect("login")  # after logout, send user to login page

recipes/templates/recipes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{object.name}}</title>
  <link rel="stylesheet" href="{% static 'recipes/css/detail.css' %}">
</head>
<body>
  <button><a href="{% url 'recipes:list' %}">Back</a></button>
  <div class="center-content">
    <h1>Recipe - {{object.name}}</h1>
    <b>Ingredients: </b> {{object.ingredients}} <br /><br />
    <b>Cooking Time: </b> {{object.cooking_time}} minutes<br /><br />
    <b>Difficulty: </b> {{object.difficulty}} <br /><br />
    <img src="{{object.pic.url}}" width="200" />
  </div>
</body>
</html>

recipes/templates/recipes/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'recipes/css/home.css' %}" />
  </head>
  <body>
    <h1>Welcome to the home page</h1>
    
    <button><a href="{%url 'login' %}"> Login </a></button>  </body>
</html>

recipes/templates/recipes/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Recipes</title>
  <link rel="stylesheet" href="{% static 'recipes/css/main.css' %}">
</head>
<body>
  <button>
  <a href="{%url 'logout' %}"> Logout </a></button>
  <button>
  <a href="{%url 'recipes:search' %}"> Search </a></button>
  
  <h1>Recipes' list</h1>
{% comment%} HTML tag for heading {% endcomment%}

<table border="1" cellpadding="5" cellspacing="5">
  {% comment%} start of table {% endcomment%}
  <tr>
    {% comment%} the
  </tr>
  <tr>
    tag adds a new row {% endcomment%}
    <td>Recipes' Titles</td>
    {% comment%} the
    <td>tag adds a column {% endcomment%}</td>
    <td>Recipes Images</td>
  </tr>
  {% for object in object_list %} {% comment%} go through each element of recipes'
  list {% endcomment%}
  <tr>
    <td><button>
      <a href="{{object.get_absolute_url}}">
        {% comment%} add links to recipe names {% endcomment%} {{object.name}}
      </a></button>
    </td>
    <td><img src="{{object.pic.url}}" width="150" /></td>
  </tr>
  {% endfor %}
</table>
</body>
</html>

recipes/templates/recipes/search.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'recipes/css/search.css' %}">
</head>
<body>
  <h1>Search for recipes</h1>

<hr />
<form action="" method="POST">
  {% csrf_token %} 
  {{form}}
  <button type="submit">search</button>
  <hr>
  {% if recipes_df %}
   {{recipes_df|safe}} 
  {% else %}
   <h3> no data</h3>
  {% endif %}
</form>
</body>
</html>